declare module "lucide-react" {
  import type { FC, SVGProps } from "react";
  interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
  type Icon = FC<IconProps>;
  export const AlertCircle: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const Atom: Icon;
  export const Award: Icon;
  export const BookHeart: Icon;
  export const BookOpen: Icon;
  export const Calendar: Icon;
  export const Camera: Icon;
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const ChevronDown: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ClipboardCheck: Icon;
  export const Clock: Icon;
  export const Code: Icon;
  export const Compass: Icon;
  export const Cpu: Icon;
  export const Eye: Icon;
  export const FileCheck: Icon;
  export const Flame: Icon;
  export const Footprints: Icon;
  export const Globe: Icon;
  export const GraduationCap: Icon;
  export const HandHeart: Icon;
  export const Heart: Icon;
  export const Home: Icon;
  export const Lightbulb: Icon;
  export const Loader2: Icon;
  export const Mail: Icon;
  export const MapPin: Icon;
  export const Menu: Icon;
  export const MessageSquare: Icon;
  export const Palette: Icon;
  export const PartyPopper: Icon;
  export const Phone: Icon;
  export const Quote: Icon;
  export const Rocket: Icon;
  export const School: Icon;
  export const Search: Icon;
  export const Shield: Icon;
  export const ShieldCheck: Icon;
  export const ShoppingBag: Icon;
  export const Sparkles: Icon;
  export const Star: Icon;
  export const Target: Icon;
  export const Trophy: Icon;
  export const UserCheck: Icon;
  export const UserPlus: Icon;
  export const Users: Icon;
  export const X: Icon;
}
